export * from "./Header/Header";
export * from "./MoviesListCard/MoviesListCard";
export * from "./MovieInfo/MovieInfo";
export * from "./MoviesList/MoviesList";
export * from "./Footer/Footer";
export * from "./UserInfo/UserInfo";
export * from "./GenreBadge/GenreBadge";
export * from "./Stars/StarsRating";
export * from "./Switch/Switch";